# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MANFAI.ME
description: >-
  I pursued my Bachelors in Multimedia Computing from Coventry University. 
  About my profession, now I am web programmer where I work on various programming languages ​​such as 
  PHP, JavaScript, Jquery, Vue.js, Node.js, Python.
introduction: >- # this means to ignore newlines until "baseurl:"
  Jekyll is a website generator that's designed for building minimal, static blogs to be hosted on GitHub Pages.
  Today I'm just doing my part in getting away from a platform that should be forgotten. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manfai.me" # the base hostname & protocol for your site, e.g. http://example.com
daisyui_theme: lofi

email: iam@manfai.me
name: Man Wing Fai
bio: I pursued my Bachelors in Multimedia Computing from Coventry University. About my profession, now I am web programmer where I work on various programming languages ​​such as PHP, JavaScript, Jquery, Vue.js, Node.js, Python.
last_name: Man
first_name: Wing Fai
phone: +(852) 9351 7034
dob: "1993-10-06"
gender: male
job_title: Full-Stack Developer
address: Yuen Long
citizenship: China/PRC
residence: Hong Kong

twitter_username: manfai106
github_username:  manfai
linkedin_username:  wingfai-man

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
  
sass:
  load_paths:
    - _sass
    - node_modules

include: ['_pages', 'node_modules/tailwindcss']

excerpt_separator: <!--more-->
permalink: pretty
collections_dir: collections
collections:
  pages:
    output: true
    permalink: /:path
  experiences:
    output: true
    permalink: /:collection/:year/:month/:title:output_ext
  projects:
    output: true
    permalink: /portfolio/:title:output_ext
  achievements:
    output: true
    permalink: /achievement/:year/:month/:title:output_ext
  quotation:
    output: true
    permalink: /quotation/:title:output_ext

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "achievements"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "quotation"
    values:
      layout: "quote"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: false
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/images"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################